String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Jeremiah',
    '%4'                    : 'Tamara',
    '%8'                    : 'Weedgenaelle',
    '%16'                   : 'natalia',
    '%32'                   : 'logan',
    '%64'                   : 'nyilton',
    '%128'                  : 'gaby',
    '%256'                  : 'shaneka',
    '%512'                  : 'benen',
    '%1024'                 : 'meerab',
    '%2048'                 : 'julian',
    '%4096'                 : 'hannah',
    '%8192'                 : 'jolicia',
    '%p0'                   : 'Jeremiah',
    '%p4'                   : 'Tamara',
    '%p8'                   : 'Weedgenaelle',
    '%p16'                  : 'natalia',
    '%p32'                  : 'logan',
    '%p64'                  : 'nyilton',
    '%p128'                 : 'gaby',
    '%p256'                 : 'shaneka',
    '%p512'                 : 'benen',
    '%p1024'                : 'meerab',
    '%p2048'                : 'julian',
    '%p4096'                : 'hannah',
    '%p8192'                : 'jolicia'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Friends!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Jeremiah',
    '%4'                    : 'Tamara',
    '%8'                    : 'Weedgenaelle',
    '%16'                   : 'natalia',
    '%32'                   : 'logan',
    '%64'                   : 'nyilton',
    '%128'                  : 'gaby',
    '%256'                  : 'shaneka',
    '%512'                  : 'benen',
    '%1024'                 : 'meerab',
    '%2048'                 : 'julian',
    '%4096'                 : 'hannah',
    '%8192'                 : 'jolicia',
    '%p0'                   : 'Jeremiah',
    '%p4'                   : 'Tamara',
    '%p8'                   : 'Weedgenaelle',
    '%p16'                  : 'natalia',
    '%p32'                  : 'logan',
    '%p64'                  : 'nyilton',
    '%p128'                 : 'gaby',
    '%p256'                 : 'shaneka',
    '%p512'                 : 'benen',
    '%p1024'                : 'meerab',
    '%p2048'                : 'julian',
    '%p4096'                : 'hannah',
    '%p8192'                : 'jolicia'
  }

});
